id: P88842AA5
initial_creation_type: input
source_metadata:
  title: Vajrakīla Series
  language: de
  description: 'A series of texts related to the deity Vajrakīla or Vajrakīlaya (rdo
    rje phur ba):'
  volume:
    677c50ca52874d81ac744e219c09798d:
      title: A Short Practice for Averting Obstacles through Vajrakīla
      parent: Averting Obstacles
    a74912f9a5fe4bf2bb957d6ef1fd0cc1:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Commentaries
    5bda77ba0f824145b19f3e4b2563cd92:
      title: 'Offering Clouds of Samantabhadra: Confession and Fulfilment'
      parent: Confession and Fulfilment
    bb2a94bc0b1741dea5dc44aa6291dd2e:
      title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for
        the ''Neck-Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Fire Offering
    ea09c404adfb42a8baa13a2fc6475bce:
      title: 'Inventory: The Perfectly Clear Mirror from the Razor of the Innermost
        Essence'
      parent: Inventories
    ba075578b2ff4edbaf5609b887899654:
      title: 'The Swift Infusion of Blessings: A Lineage Prayer for the Single Mind
        Kīla Heart-Practice, Part of the ''Neck Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Lineage Prayers
    9f4b46fa3aa4403290cece6e05a357a9:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Lineage Prayers
    3ecac78019f842ce8e97b9aae3bc085e:
      title: A Vajrakīla Lineage Prayer
      parent: Lineage Prayers
    ecda02c7222d46a8920e69928caa05ea:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Offering
    2456987d0d4047bdb2bbae610f2db66b:
      title: The Eight-Branch Offering from the Gyüluk Phurba
      parent: Offering
    7e382bf52b434b209131162ee1e816cc:
      title: Invocation of the Vidyādhara Gurus
      parent: Prayers
    80438bc3972e4e67aa618deba1eb884c:
      title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
      parent: Prayers
    2423962465294410847e6968661b6a6e:
      title: The Summoning of Blessings which Brings them Swift and Fast
      parent: Prayers
    9061740fd238484292ec74da6507fe2c:
      title: Entrusting Activity
      parent: Protectors
    24442b2287e4472abb7fef907edeb6f7:
      title: Offering to the Dharma Guardians of the 'Neck-Pouch Dagger’ (Purba Gulkhukma)
        Cycle
      parent: Protectors
    9e75008db30c47c8a24d3303e2899508:
      title: Daily Practice of Vajrakīla
      parent: Sādhanas
    2a167df3c08b434db1bf7a5785f8300a:
      title: The Essential Daily Practice of Vajrakīla
      parent: Sādhanas
    d3d51c45ae004007b95c423473bbdc8a:
      title: 'The Accomplishment of Supreme Enlightened Activity: A Recitation Manual
        for The Vajrakīla Root Tantra Section'
      parent: Sādhanas
    5a769f17e69446538ce669313fd7222b:
      title: 'Inlaid Jewels: Addenda to the ''Neck-Pouch Dagger’ (Purba Gulkhukma)
        Cycle'
      parent: Sādhanas
    ddb3566f810b40ceae43b00ab051ae01:
      title: The Single Mind Kīla Practice, Part of the 'Neck-Pouch Dagger’ (Purba
        Gulkhukma) Cycle
      parent: Sādhanas
    e75c97701b19454cae69c72a9d133aac:
      title: The Wisdom Mind Practice of One Kīla
      parent: Sādhanas
    7fb0d48c05e34a5385f8a5a81a40a002:
      title: A Section of the Vajrakīla Root Tantra
      parent: Tantras
created_at: '2022-03-01T06:29:47.477895'
last_modified_at: '2022-03-01T06:29:47.477898'
